### ISSUE TITLE
[PE-D][Tester E] Check client feature may not be working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-1/tp#157] opened 2022-10-28 16:37 UTC
![Screenshot 2022-10-28 at 5.04.40 PM.png](https://raw.githubusercontent.com/jorellesee/ped/main/files/e89f428a-d71b-491b-bad5-acd0100cb7cc.png)

![Screenshot 2022-10-28 at 5.04.55 PM.png](https://raw.githubusercontent.com/jorellesee/ped/main/files/fe0abb49-3e7d-49c3-baba-120cdaa0a961.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jorellesee/ped#7

**Comment by ngdeqi** [comment] 2022-10-29 05:57
Closed as duplicate of #161

**Closed as not planned by ngdeqi** 2022-10-29 05:57 UTC
