### ISSUE TITLE
[PE-D][Tester B] UG instructions of "check" is unclear

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-1/tp#184] opened 2022-10-28 16:51 UTC
![Screenshot 2022-10-28 at 19.15.01.png](https://raw.githubusercontent.com/HT-T/ped/main/files/58eb7a33-5fdd-4562-9eb9-8f72a0414610.png)

The actual command for checking a client is ```check -client ic/INDEX``` 

Both the format and example here could be misleading.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: HT-T/ped#11

**Comment by ngdeqi** [comment] 2022-10-29 05:49
Closed as it is duplicate of #161

**Closed as not planned by ngdeqi** 2022-10-29 05:49 UTC
Labels: type.Bug, severity.Medium
